# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgstream < Formula
  desc "PostgreSQL replication with DDL changes"
  homepage "https://www.xata.io"
  version "0.9.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xataio/pgstream/releases/download/v0.9.8/pgstream.macos.amd64"
      sha256 "f91ba93d6d7e52d3af0cd2b713e7380b530eb5c37624e5c805b0afa24dbd92f0"

      define_method(:install) do
        bin.install "pgstream.macos.amd64" => "pgstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xataio/pgstream/releases/download/v0.9.8/pgstream.macos.arm64"
      sha256 "d47991ec05e55377666cdf32b394cf8c0e12b0cee12d19887daf50a30de847e1"

      define_method(:install) do
        bin.install "pgstream.macos.arm64" => "pgstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xataio/pgstream/releases/download/v0.9.8/pgstream.linux.amd64"
      sha256 "a5df4c216382421b7ec25542a66108c78727b61747be1982cd3e3292a7d65e0e"
      define_method(:install) do
        bin.install "pgstream.linux.amd64" => "pgstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xataio/pgstream/releases/download/v0.9.8/pgstream.linux.arm64"
      sha256 "777192e3c0cad223089972c9f192dc7575cb91d186d26045c0a064cfd3a32b2c"
      define_method(:install) do
        bin.install "pgstream.linux.arm64" => "pgstream"
      end
    end
  end
end
